
name: Build & Upload Installer Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ✅ Official GitHub checkout action (verified)
    - name: Checkout repository
      uses: actions/checkout@v4

    # ✅ Use local steps for PHP setup instead of third-party
    - name: Install PHP, Composer, Node.js
      run: |
        sudo add-apt-repository ppa:ondrej/php -y
        sudo apt-get update
        sudo apt-get install -y php8.3 php8.3-cli php8.3-mbstring php8.3-xml php8.3-mysql php8.3-sqlite3 unzip curl git
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        sudo apt-get install -y npm
        npm install -g npm@latest

    # ✅ Install dependencies
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    # ✅ Build frontend
    - name: Install & build frontend
      run: |
        npm ci
        npm run build

    # ✅ Create source archives
    - name: Create source.zip and source.tar.gz
      run: |
        git archive --format zip --output source-${{ github.ref_name }}.zip HEAD
        git archive --format tar.gz --output source-${{ github.ref_name }}.tar.gz HEAD

    # ✅ Prepare build structure once
    - name: Prepare common build structure
      run: |
        mkdir -p build_common
        cp -r app bootstrap config database public resources routes plugins build_common/
        cp composer.json composer.lock artisan server.php install.sql install57.sql build_common/
        cp env_install build_common/.env
        cp yvsou_install_config.php build_common/config/yvsou_config.php   
        cp *.* build_common/ || true
        rm -f build_common/*.sh || true
        cp composer.sh build_common/ || true

        mkdir -p build_common/storage/app/{private,public,protected-files}
        mkdir -p build_common/storage/framework/{cache,sessions,testing,views}
        mkdir -p build_common/storage/logs
        cp storage/tmp-install.sqlite build_common/storage/tmp-install.sqlite || true

    # ✅ Build installer.zip
    - name: Build installer.zip
      run: |
        mkdir -p staging/yvsou-cms
        cp -r build_common/* staging/yvsou-cms/
        cd staging
        zip -r ../installer-${{ github.ref_name }}.zip yvsou-cms \
          --exclude='**/*.log' --exclude='node_modules/*' --exclude='.git/*' --exclude='bootstrap/cache/*.php'

    # ✅ Build installvendor.zip
    - name: Build installvendor.zip
      run: |
        cd ..
        cp -r vendor build_common/
        mkdir -p staging_vendor/yvsou-cms
        cp -r build_common/* staging_vendor/yvsou-cms/
        cd staging_vendor
        zip -r ../installvendor-${{ github.ref_name }}.zip yvsou-cms \
          --exclude='**/*.log' --exclude='node_modules/*' --exclude='.git/*' --exclude='bootstrap/cache/*.php'

    # ✅ Generate SHA-256 checksums
    - name: Generate SHA-256 checksums
      run: |
        sha256sum *.zip > checksums-sha256.txt
        sha256sum *.tar.gz >> checksums-sha256.txt
        cat checksums-sha256.txt

    # ✅ Use official GitHub CLI to upload releases
    - name: Upload release assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} \
          installer-${{ github.ref_name }}.zip \
          installvendor-${{ github.ref_name }}.zip \
          source-${{ github.ref_name }}.zip \
          source-${{ github.ref_name }}.tar.gz \
          checksums-sha256.txt --clobber
