name: Track GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # Needed to push to main

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: python docs/track_metrics.py

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/metrics/*.csv
          git commit -m "📈 Auto-update metrics $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
 